# version: '3.8' # Removed as it's obsolete in newer Docker Compose versions

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: gift-tracker-postgres
    environment:
      POSTGRES_DB: gift_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - gift-tracker-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d gift_tracker" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Traefik Reverse Proxy
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/certificates/acme.json
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certificates:/certificates
      - ./traefik/dynamic/config.yml:/etc/traefik/dynamic/config.yml:ro
    networks:
      - gift-tracker-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth-traefik"
      - "traefik.http.middlewares.auth-traefik.basicauth.users=admin:$$2b$$10$$Fdw5jIrGATIQtqCibFXXV.CuN2BfKAHJDLmQhMBM.6vFk3NxAnsMu"
    restart: unless-stopped

  # Admin Panel
  admin-panel:
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    container_name: admin-panel
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gift_tracker
      - DB_USER=admin
      - DB_PASSWORD=${DB_PASSWORD:-admin123}
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - gift-tracker-network
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.${DOMAIN}`)"
      - "traefik.http.routers.admin.tls=true"
      - "traefik.http.routers.admin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.admin.service=admin-panel"
      - "traefik.http.services.admin-panel.loadbalancer.server.port=3000"
    restart: unless-stopped

  # Gift Tracker Example Instance
  gift-tracker-example:
    build:
      context: ./gift-tracker-instance
      dockerfile: Dockerfile
    container_name: gift-tracker-example
    environment:
      - TIKTOK_USERNAME=example_user
      - DASH_PASSWORD=example_password
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gift_tracker
      - DB_USER=admin
      - DB_PASSWORD=${DB_PASSWORD:-admin123}
    volumes:
      - ./data/instances/example:/app/data
    networks:
      - gift-tracker-network
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gift-example.rule=Host(`gift-tracker-example.${DOMAIN}`)"
      - "traefik.http.routers.gift-example.tls=true"
      - "traefik.http.routers.gift-example.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gift-example.service=gift-example"
      - "traefik.http.services.gift-example.loadbalancer.server.port=3000"
      - "traefik.http.routers.gift-example.middlewares=auth-example"
      - "traefik.http.middlewares.auth-example.basicauth.users=admin:$$2b$$10$$Fdw5jIrGATIQtqCibFXXV.CuN2BfKAHJDLmQhMBM.6vFk3NxAnsMu"
    restart: unless-stopped

networks:
  gift-tracker-network:
    driver: bridge

volumes:
  postgres_data:
