# Traefik Configuration
api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: gift-tracker-multi-tenant_gift-tracker-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@o3-ttgifts.com
      storage: /etc/traefik/certificates/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}

# Global settings
global:
  checkNewVersion: false
  sendAnonymousUsage: false
